# COCO 2017 dataset http://cocodataset.org

data:
  dataset_name: coco

  train_set: ./coco/train2017.txt  # 118287 images
  val_set: ./coco/val2017.txt  # 5000 images
  test_set: ./coco/test-dev2017.txt  # 20288 of 40670 images, submit to https://competitions.codalab.org/competitions/20794

  nc: 1

  # class names
  names: [ 'object' ]

  train_transforms: []
  test_transforms: []